version: '3.9'

services:
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sistema_contable
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  tailwind:
    image: node-img-test
    build:
      context: .
      dockerfile: dockerfile.node
    container_name: tailwind-test
    volumes:
      - ./backend/sic/src/main/resources/static/css:/app/css
      - ./backend/sic/src/main/resources/templates:/app/templates
      - ./backend/sic/src/main/resources/static/js:/app/js
    tty: true
    stdin_open: true

volumes:
  pgdata: {}
